language: node_js
node_js:
  - "4.4"
  - "5.11"
  - "6.2"
sudo: required
services:
  - redis-server
before_install:
  - "sudo apt-get install graphicsmagick"
script: "npm run-script test-ci"
after_script: "npm install coveralls@2.10.0 && cat ./coverage/lcov.info | coveralls"
