
# Test against these versions of Node.js.
environment:
  matrix:
    - nodejs_version: "0.10"
    - nodejs_version: "0.11"
    - nodejs_version: "0.12"
    - nodejs_version: "3.0"
    - nodejs_version: "4.0"
    - nodejs_version: "4.1"

# Install scripts. (runs after repo cloning)
install:
  # Install the GraphicsMagick
  - appveyor DownloadFile http://downloads.sourceforge.net/graphicsmagick/GraphicsMagick-1.3.20-Q8-win32-dll.exe
  - GraphicsMagick-1.3.20-Q8-win32-dll.exe /SP /VERYSILENT /NORESTART /NOICONS /DIR=%CD%\gm
  - set PATH=%CD%\gm;%PATH%
  # Install the Redis
  - nuget install redis-64 -excludeversion
  - redis-64\redis-server.exe --service-install
  - redis-64\redis-server.exe --service-start
  - '@ECHO Redis Started'
  # Get the latest stable version of Node 0.STABLE.latest
  - ps: Install-Product node $env:nodejs_version
  # Typical npm stuff.
  - npm install

# Post-install test scripts.
test_script:
  # Output useful info for debugging.
  - node --version
  - npm --version
  - cmd: test ! -z $(npm -ps ls istanbul) || npm test

os:
  - Default Azure
  - Windows Server 2012 R2

# Don't actually build using MSBuild
build: off

# Set build version format here instead of in the admin panel.
version: "{build}"